services:
  - type: web
    name: fraud-detection-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: fraud-detection-dashboard
    runtime: docker
    dockerfilePath: ./Dockerfile.dashboard
    plan: free
    envVars:
      - key: PORT
        value: 8501
